"""add date column to UserExercises table

Revision ID: f813deed9af1
Revises: 8f31bdd3740e
Create Date: 2024-03-24 22:35:07.044082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f813deed9af1'
down_revision = '8f31bdd3740e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercises', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
